- Add edit command + refactor repli file arg

diff --git a/repli b/repli
--- a/repli
+++ b/repli
@@ -28,6 +28,7 @@ repli_usage() {
   printf "%s\n" "$(bold "Commands:")"
   printf "  %s   Create a new configuration file from a tmeplate\n" "$(green "new")      "
   printf "  %s   Call Replicate using a configuration file and save the result\n" "$(green "get")      "
+  printf "  %s   Edit the repli file\n" "$(green "edit")     "
   printf "  %s   Get information on a model\n" "$(green "info")     "
   printf "  %s   Manage templates\n" "$(green "templates")"
   printf "  %s   Manage uploaded files\n" "$(green "files")    "
@@ -100,7 +101,7 @@ repli_new_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(green "--output, -o PATH")"
+    printf "  %s\n" "$(green "--use, -u PATH")"
     printf "    Path to target repli file\n"
     printf "    %s\n" "Default: $REPLI_FILE"
     echo
@@ -155,7 +156,7 @@ repli_get_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(green "--config, -c PATH")"
+    printf "  %s\n" "$(green "--use, -u PATH")"
     printf "    Path to repli file\n"
     printf "    %s\n" "Default: $REPLI_FILE"
     echo
@@ -171,6 +172,37 @@ repli_get_usage() {
     # :argument.usage
     printf "  %s\n" "$(green "PREFIX")"
     printf "    Prefix for saved JSON file and output files\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+repli_edit_usage() {
+  printf "repli edit - Edit the repli file\n\n"
+  printf "Alias: e\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  repli edit [OPTIONS]\n"
+  printf "  repli edit --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(green "--use, -u PATH")"
+    printf "    Path to repli file\n"
+    printf "    %s\n" "Default: $REPLI_FILE"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(green "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -1003,7 +1035,7 @@ repli_new_command() {
 
   # src/commands/new.sh
   search="${args[search]}"
-  outfile="${args[--output]}"
+  outfile="${args[--use]}"
   force="${args[--force]}"
   exact="${args[--exact]}"
 
@@ -1057,8 +1089,9 @@ repli_new_command() {
 repli_get_command() {
 
   # src/commands/get.sh
-  config="${args[--config]}"
-  prefix="${args[prefix]:-$(get_unique_filename "$(basename "$repli_file" ".yaml")")}"
+  config="${args[--use]}"
+  prefix="${args[prefix]:-$(get_unique_filename "$(basename "$config" ".yaml")")}"
+
   outfile="${prefix}.json"
   log debug config: "$(blue "$config")"
   log debug prefix: "$(blue "$prefix")"
@@ -1074,6 +1107,15 @@ repli_get_command() {
 
   # download outputs
   download_outputs "$prefix" "$outfile"
+
+}
+
+# :command.function
+repli_edit_command() {
+
+  # src/commands/edit.sh
+  config="${args[--use]}"
+  "${EDITOR}" "$config"
 
 }
 
@@ -1325,6 +1367,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    edit | e)
+      action="edit"
+      shift
+      repli_edit_parse_requirements "$@"
+      shift $#
+      ;;
+
     info | i)
       action="info"
       shift
@@ -1411,15 +1460,15 @@ repli_new_parse_requirements() {
     key="$1"
     case "$key" in
       # :flag.case
-      --output | -o)
+      --use | -u)
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          args['--output']="$2"
+          args['--use']="$2"
           shift
           shift
         else
-          printf "%s\n" "--output requires an argument: --output, -o PATH" >&2
+          printf "%s\n" "--use requires an argument: --use, -u PATH" >&2
           exit 1
         fi
         ;;
@@ -1463,7 +1512,7 @@ repli_new_parse_requirements() {
   done
 
   # :command.default_assignments
-  [[ -n ${args['--output']:-} ]] || args['--output']="$REPLI_FILE"
+  [[ -n ${args['--use']:-} ]] || args['--use']="$REPLI_FILE"
 
   # :command.user_filter
   filter_error=$(filter_templates_dir_exists)
@@ -1503,15 +1552,15 @@ repli_get_parse_requirements() {
     key="$1"
     case "$key" in
       # :flag.case
-      --config | -c)
+      --use | -u)
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          args['--config']="$2"
+          args['--use']="$2"
           shift
           shift
         else
-          printf "%s\n" "--config requires an argument: --config, -c PATH" >&2
+          printf "%s\n" "--use requires an argument: --use, -u PATH" >&2
           exit 1
         fi
         ;;
@@ -1539,14 +1588,87 @@ repli_get_parse_requirements() {
   done
 
   # :command.default_assignments
-  [[ -n ${args['--config']:-} ]] || args['--config']="$REPLI_FILE"
+  [[ -n ${args['--use']:-} ]] || args['--use']="$REPLI_FILE"
 
   # :command.validations
   # :flag.validations
-  if [[ -v args['--config'] ]]; then
-    validation_output="$(validate_file_exists "${args['--config']:-}")"
+  if [[ -v args['--use'] ]]; then
+    validation_output="$(validate_file_exists "${args['--use']:-}")"
     if [[ -n "${validation_output}" ]]; then
-      printf "validation error in %s:\n%s\n" "--config, -c PATH" "$validation_output" >&2
+      printf "validation error in %s:\n%s\n" "--use, -u PATH" "$validation_output" >&2
+      exit 1
+    fi
+  fi
+
+}
+
+# :command.parse_requirements
+repli_edit_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        repli_edit_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="edit"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --use | -u)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--use']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--use requires an argument: --use, -u PATH" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--use']:-} ]] || args['--use']="$REPLI_FILE"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--use'] ]]; then
+    validation_output="$(validate_file_exists "${args['--use']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--use, -u PATH" "$validation_output" >&2
       exit 1
     fi
   fi
@@ -2410,6 +2532,7 @@ run() {
   case "$action" in
     "new") repli_new_command ;;
     "get") repli_get_command ;;
+    "edit") repli_edit_command ;;
     "info") repli_info_command ;;
     "templates") repli_templates_command ;;
     "templates new") repli_templates_new_command ;;
