- Add more template management commands

diff --git a/repli b/repli
--- a/repli
+++ b/repli
@@ -249,8 +249,11 @@ repli_templates_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
-  printf "  %s   Add a new template from a remote Replicate model example\n" "$(green "new") "
-  printf "  %s   Show list of templates\n" "$(green "list")"
+  printf "  %s   Add a new template from a remote Replicate model example\n" "$(green "new")   "
+  printf "  %s   Show list of templates\n" "$(green "list")  "
+  printf "  %s   Show template\n" "$(green "show")  "
+  printf "  %s   Open template in editor\n" "$(green "edit")  "
+  printf "  %s   Delete template file\n" "$(green "delete")"
   echo
 
   # :command.long_usage
@@ -342,6 +345,111 @@ repli_templates_list_usage() {
     # :argument.usage
     printf "  %s\n" "$(green "SEARCH")"
     printf "    Template search string\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+repli_templates_show_usage() {
+  printf "repli templates show - Show template\n\n"
+  printf "Alias: s\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  repli templates show TEMPLATE\n"
+  printf "  repli templates show --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(green "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "$(green "TEMPLATE")"
+    printf "    Template name\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+repli_templates_edit_usage() {
+  printf "repli templates edit - Open template in editor\n\n"
+  printf "Alias: e\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  repli templates edit TEMPLATE\n"
+  printf "  repli templates edit --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(green "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "$(green "TEMPLATE")"
+    printf "    Template name\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "%s\n" "$(bold "Environment Variables:")"
+
+    # :environment_variable.usage
+    printf "  %s\n" "$(green "EDITOR")"
+    printf "    Editor to use\n"
+    printf "    %s\n" "Default: vi"
+    echo
+
+  fi
+}
+
+# :command.usage
+repli_templates_delete_usage() {
+  printf "repli templates delete - Delete template file\n\n"
+  printf "Alias: d, del, rm\n"
+  echo
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  repli templates delete TEMPLATE\n"
+  printf "  repli templates delete --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(green "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "$(green "TEMPLATE")"
+    printf "    Template name\n"
     echo
 
   fi
@@ -603,6 +711,13 @@ download_outputs() {
   done
 }
 
+# src/lib/filters/templates_dir_exist.sh
+filter_templates_dir_exists() {
+  if [[ ! -d "$templates_dir" ]]; then
+    echo "Templates dir not found ($templates_dir), set using REPLI_TEMPLATES_DIR"
+  fi
+}
+
 # src/lib/get_example_from_replicate.sh
 get_example_from_replicate() {
   json=$(get_model_info "$model") || return 1
@@ -811,31 +926,38 @@ upload_to_replicate() {
   echo "$input_file_url"
 }
 
-# src/lib/validations/validate_dir_exists.sh
+# src/lib/validations/dir_exists.sh
 validate_dir_exists() {
   if [[ ! -d "$1" ]]; then
     echo "must be an existing directory"
   fi
 }
 
-# src/lib/validations/validate_file_exists.sh
+# src/lib/validations/file_exists.sh
 validate_file_exists() {
   if [[ ! -f "$1" ]]; then
     echo "must be an existing file"
   fi
 }
 
-# src/lib/validations/validate_integer.sh
+# src/lib/validations/integer.sh
 validate_integer() {
   if ! [[ "$1" =~ ^[0-9]+$ ]]; then
     echo "must be an integer"
   fi
 }
 
-# src/lib/validations/validate_model_name.sh
+# src/lib/validations/model_name.sh
 validate_model_name() {
   if ! [[ "$1" =~ ^[^/]+/[^/]+$ ]]; then
     echo "must be in the form of author/model"
+  fi
+}
+
+# src/lib/validations/template_exists.sh
+validate_template_exists() {
+  if [[ ! -f "$templates_dir/$1.yaml" ]]; then
+    echo "must be an existing template"
   fi
 }
 
@@ -884,12 +1006,6 @@ repli_new_command() {
   outfile="${args[--output]}"
   force="${args[--force]}"
   exact="${args[--exact]}"
-
-  if [[ ! -d "$templates_dir" ]]; then
-    log error "no templates in $(blue "$templates_dir")"
-    log info "change templates dir using $(blue REPLI_TEMPLATES_DIR)"
-    return 1
-  fi
 
   # Do not overwrite unless --force is used
   if [[ -e "$outfile" && -z "$force" ]]; then
@@ -1021,14 +1137,38 @@ repli_templates_list_command() {
 
   # src/commands/templates/list.sh
   search="${args[search]}"
-
-  if [[ ! -d "$templates_dir" ]]; then
-    log error "templates dir not found: $(blue "$templates_dir")"
-    log info "change templates dir using $(blue REPLI_TEMPLATES_DIR)"
-    return 1
-  fi
-
   show_templates_list "$search"
+
+}
+
+# :command.function
+repli_templates_show_command() {
+
+  # src/commands/templates/show.sh
+  template="${args[template]}"
+  file="$templates_dir/$template.yaml"
+  yq -P -oy "$file"
+
+}
+
+# :command.function
+repli_templates_edit_command() {
+
+  # src/commands/templates/edit.sh
+  template="${args[template]}"
+  file="$templates_dir/$template.yaml"
+  "${EDITOR}" "$file"
+
+}
+
+# :command.function
+repli_templates_delete_command() {
+
+  # src/commands/templates/delete.sh
+  template="${args[template]}"
+  file="$templates_dir/$template.yaml"
+  log info "deleting $file"
+  rm "$file"
 
 }
 
@@ -1325,6 +1465,13 @@ repli_new_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--output']:-} ]] || args['--output']="$REPLI_FILE"
 
+  # :command.user_filter
+  filter_error=$(filter_templates_dir_exists)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
 }
 
 # :command.parse_requirements
@@ -1562,6 +1709,27 @@ repli_templates_parse_requirements() {
       shift $#
       ;;
 
+    show | s)
+      action="show"
+      shift
+      repli_templates_show_parse_requirements "$@"
+      shift $#
+      ;;
+
+    edit | e)
+      action="edit"
+      shift
+      repli_templates_edit_parse_requirements "$@"
+      shift $#
+      ;;
+
+    delete | d | del | rm)
+      action="delete"
+      shift
+      repli_templates_delete_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       repli_templates_usage >&2
@@ -1745,6 +1913,250 @@ repli_templates_list_parse_requirements() {
 
     esac
   done
+
+  # :command.user_filter
+  filter_error=$(filter_templates_dir_exists)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+repli_templates_show_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        repli_templates_show_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="templates show"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['template']+x} ]]; then
+          args['template']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['template']+x} ]]; then
+    printf "missing required argument: TEMPLATE\nusage: repli templates show TEMPLATE\n" >&2
+
+    exit 1
+  fi
+
+  # :command.validations
+  # :argument.validations
+  if [[ -v args['template'] ]]; then
+    validation_output="$(validate_template_exists "${args['template']:-}")"
+    if [[ -n "$validation_output" ]]; then
+      printf "validation error in %s:\n%s\n" "TEMPLATE" "$validation_output" >&2
+      exit 1
+    fi
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_templates_dir_exists)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+repli_templates_edit_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        repli_templates_edit_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.environment_variables_filter
+  # :command.environment_variables_default
+  export EDITOR="${EDITOR:-vi}"
+
+  env_var_names+=("EDITOR")
+
+  # :command.command_filter
+  action="templates edit"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['template']+x} ]]; then
+          args['template']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['template']+x} ]]; then
+    printf "missing required argument: TEMPLATE\nusage: repli templates edit TEMPLATE\n" >&2
+
+    exit 1
+  fi
+
+  # :command.validations
+  # :argument.validations
+  if [[ -v args['template'] ]]; then
+    validation_output="$(validate_template_exists "${args['template']:-}")"
+    if [[ -n "$validation_output" ]]; then
+      printf "validation error in %s:\n%s\n" "TEMPLATE" "$validation_output" >&2
+      exit 1
+    fi
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_templates_dir_exists)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+repli_templates_delete_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        repli_templates_delete_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="templates delete"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['template']+x} ]]; then
+          args['template']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['template']+x} ]]; then
+    printf "missing required argument: TEMPLATE\nusage: repli templates delete TEMPLATE\n" >&2
+
+    exit 1
+  fi
+
+  # :command.validations
+  # :argument.validations
+  if [[ -v args['template'] ]]; then
+    validation_output="$(validate_template_exists "${args['template']:-}")"
+    if [[ -n "$validation_output" ]]; then
+      printf "validation error in %s:\n%s\n" "TEMPLATE" "$validation_output" >&2
+      exit 1
+    fi
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_templates_dir_exists)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
 
 }
 
@@ -2002,6 +2414,9 @@ run() {
     "templates") repli_templates_command ;;
     "templates new") repli_templates_new_command ;;
     "templates list") repli_templates_list_command ;;
+    "templates show") repli_templates_show_command ;;
+    "templates edit") repli_templates_edit_command ;;
+    "templates delete") repli_templates_delete_command ;;
     "files") repli_files_command ;;
     "files list") repli_files_list_command ;;
     "files upload") repli_files_upload_command ;;
