add upload command

diff --git a/repli b/repli
--- a/repli
+++ b/repli
@@ -26,7 +26,8 @@ repli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Call Replicate using a configuration file and save the result (default)\n" "get"
+  printf "  %s   Upload a file to Replicate\n" "upload"
+  printf "  %s   Call Replicate using a configuration file and save the result\n" "get   "
   echo
 
   # :command.long_usage
@@ -56,13 +57,53 @@ repli_usage() {
 }
 
 # :command.usage
+repli_upload_usage() {
+  printf "repli upload - Upload a file to Replicate\n\n"
+  printf "Alias: u\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  repli upload FILE\n"
+  printf "  repli upload --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "FILE"
+    printf "    Path to file\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "%s\n" "Environment Variables:"
+
+    # :environment_variable.usage
+    printf "  %s\n" "REPLICATE_API_TOKEN (required)"
+    printf "    Replicate API token\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 repli_get_usage() {
   printf "repli get - Call Replicate using a configuration file and save the result\n\n"
   printf "Alias: g\n"
   echo
 
   printf "%s\n" "Usage:"
-  printf "  repli [get] [CONFIG] [OPTIONS]\n"
+  printf "  repli get [CONFIG] [OPTIONS]\n"
   printf "  repli get --help | -h\n"
   echo
 
@@ -251,7 +292,7 @@ download_outputs() {
     log info "downloading to $(blue "$filename")"
 
     wget -q -O "$filename" "$url" \
-      || log error "failed to download: $(blue_underlined "$url")"
+      || log error "failed to download: $(underlined "$url")"
 
   done
 }
@@ -301,6 +342,19 @@ log() {
     >&2
 }
 
+# src/lib/upload_to_replicate.sh
+upload_to_replicate() {
+  input_file="$1"
+
+  file=$(curl -s -X POST "https://api.replicate.com/v1/files" \
+    -H "Authorization: Bearer $REPLICATE_API_TOKEN" \
+    -H "Content-Type: multipart/form-data" \
+    -F "content=@$input_file;type=application/octet-stream;title=$(basename $input_file)")
+
+  input_file_url=$(echo "$file" | jq -r '.urls.get')
+  echo "$input_file_url"
+}
+
 # src/lib/validations/validate_dir_exists.sh
 validate_dir_exists() {
   if [[ ! -d "$1" ]]; then
@@ -345,10 +399,37 @@ yurl() {
 
 # :command.command_functions
 # :command.function
+repli_upload_command() {
+
+  # src/upload_command.sh
+  file="${args[file]}"
+  files_list="files.ini"
+
+  if [[ -f "$files_list" ]]; then
+    log debug reading files list: "$(blue "$files_list")"
+
+    while IFS='=' read -r path url; do
+      if [[ "$path" == "$file" ]]; then
+        log info upload skipped, already registered in "$(blue "$files_list")"
+        log info url: "$url"
+        return
+      fi
+    done < "$files_list"
+  fi
+
+  log info uploading "$(blue "$file")"
+  url="$(upload_to_replicate "$file")"
+  log info url: "$(underlined "$url")"
+
+  log info saving URL to "$(blue "$files_list")"
+  echo "$file=$url" >> "$files_list"
+
+}
+
+# :command.function
 repli_get_command() {
 
   # src/get_command.sh
-  # set variables
   config="${args[config]}"
   prefix="${args[--prefix]:-$(date +%H%M%S)}"
   outfile="${prefix}.json"
@@ -409,6 +490,14 @@ parse_requirements() {
   action=${1:-}
 
   case $action in
+    -*) ;;
+
+    upload | u)
+      action="upload"
+      shift
+      repli_upload_parse_requirements "$@"
+      shift $#
+      ;;
 
     get | g)
       action="get"
@@ -424,9 +513,8 @@ parse_requirements() {
       ;;
 
     *)
-      action="get"
-      repli_get_parse_requirements "$@"
-      shift $#
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
       ;;
 
   esac
@@ -451,6 +539,106 @@ parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+repli_upload_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        repli_upload_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.environment_variables_filter
+
+  env_var_names+=("REPLICATE_API_TOKEN")
+  if [[ -z "${REPLICATE_API_TOKEN:-}" ]]; then
+    printf "missing required environment variable: REPLICATE_API_TOKEN\n" >&2
+    exit 1
+  fi
+
+  # :command.dependencies_filter
+  missing_deps=
+  # :dependency.filter
+  if ! command -v jq >/dev/null 2>&1; then
+    printf "missing dependency: jq\n" >&2
+    missing_deps=1
+  else
+    deps['jq']="$(command -v jq | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v curl >/dev/null 2>&1; then
+    printf "missing dependency: curl\n" >&2
+    missing_deps=1
+  else
+    deps['curl']="$(command -v curl | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="upload"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['file']+x} ]]; then
+          args['file']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['file']+x} ]]; then
+    printf "missing required argument: FILE\nusage: repli upload FILE\n" >&2
+
+    exit 1
+  fi
+
+  # :command.validations
+  # :argument.validations
+  if [[ -v args['file'] ]]; then
+    validation_output="$(validate_file_exists "${args['file']:-}")"
+    if [[ -n "$validation_output" ]]; then
+      printf "validation error in %s:\n%s\n" "FILE" "$validation_output" >&2
+      exit 1
+    fi
+  fi
 
 }
 
@@ -602,6 +790,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "upload") repli_upload_command ;;
     "get") repli_get_command ;;
   esac
 }
