- Rename commands: templates > template, files > file

diff --git a/repli b/repli
--- a/repli
+++ b/repli
@@ -26,14 +26,14 @@ repli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
-  printf "  %s   Create a new configuration file from a tmeplate\n" "$(green "new")      "
-  printf "  %s   Call Replicate using a configuration file and save the result\n" "$(green "get")      "
-  printf "  %s   Edit the repli file\n" "$(green "edit")     "
-  printf "  %s   Show the repli file\n" "$(green "show")     "
-  printf "  %s   Show repli environment information\n" "$(green "env")      "
-  printf "  %s   Get information on a model\n" "$(green "info")     "
-  printf "  %s   Manage templates\n" "$(green "templates")"
-  printf "  %s   Manage uploaded files\n" "$(green "files")    "
+  printf "  %s   Create a new configuration file from a tmeplate\n" "$(green "new")     "
+  printf "  %s   Call Replicate using a configuration file and save the result\n" "$(green "get")     "
+  printf "  %s   Edit the repli file\n" "$(green "edit")    "
+  printf "  %s   Show the repli file\n" "$(green "show")    "
+  printf "  %s   Show repli environment information\n" "$(green "env")     "
+  printf "  %s   Get information on a model\n" "$(green "info")    "
+  printf "  %s   Manage templates\n" "$(green "template")"
+  printf "  %s   Manage uploaded files\n" "$(green "file")    "
   echo
 
   # :command.long_usage
@@ -331,14 +331,14 @@ repli_info_usage() {
 }
 
 # :command.usage
-repli_templates_usage() {
-  printf "repli templates - Manage templates\n\n"
+repli_template_usage() {
+  printf "repli template - Manage templates\n\n"
   printf "Alias: t\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli templates COMMAND\n"
-  printf "  repli templates [COMMAND] --help | -h\n"
+  printf "  repli template COMMAND\n"
+  printf "  repli template [COMMAND] --help | -h\n"
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
@@ -363,14 +363,14 @@ repli_templates_usage() {
 }
 
 # :command.usage
-repli_templates_new_usage() {
-  printf "repli templates new - Add a new template from a remote Replicate model example\n\n"
+repli_template_new_usage() {
+  printf "repli template new - Add a new template from a remote Replicate model example\n\n"
   printf "Alias: n, add\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli templates new MODEL [OPTIONS]\n"
-  printf "  repli templates new --help | -h\n"
+  printf "  repli template new MODEL [OPTIONS]\n"
+  printf "  repli template new --help | -h\n"
   echo
 
   # :command.long_usage
@@ -412,14 +412,14 @@ repli_templates_new_usage() {
 }
 
 # :command.usage
-repli_templates_list_usage() {
-  printf "repli templates list - Show list of templates\n\n"
+repli_template_list_usage() {
+  printf "repli template list - Show list of templates\n\n"
   printf "Alias: ls\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli templates list [SEARCH]\n"
-  printf "  repli templates list --help | -h\n"
+  printf "  repli template list [SEARCH]\n"
+  printf "  repli template list --help | -h\n"
   echo
 
   # :command.long_usage
@@ -444,14 +444,14 @@ repli_templates_list_usage() {
 }
 
 # :command.usage
-repli_templates_show_usage() {
-  printf "repli templates show - Show template\n\n"
+repli_template_show_usage() {
+  printf "repli template show - Show template\n\n"
   printf "Alias: s\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli templates show TEMPLATE\n"
-  printf "  repli templates show --help | -h\n"
+  printf "  repli template show TEMPLATE\n"
+  printf "  repli template show --help | -h\n"
   echo
 
   # :command.long_usage
@@ -476,14 +476,14 @@ repli_templates_show_usage() {
 }
 
 # :command.usage
-repli_templates_edit_usage() {
-  printf "repli templates edit - Open template in editor\n\n"
+repli_template_edit_usage() {
+  printf "repli template edit - Open template in editor\n\n"
   printf "Alias: e\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli templates edit TEMPLATE\n"
-  printf "  repli templates edit --help | -h\n"
+  printf "  repli template edit TEMPLATE\n"
+  printf "  repli template edit --help | -h\n"
   echo
 
   # :command.long_usage
@@ -517,14 +517,14 @@ repli_templates_edit_usage() {
 }
 
 # :command.usage
-repli_templates_delete_usage() {
-  printf "repli templates delete - Delete template file\n\n"
+repli_template_delete_usage() {
+  printf "repli template delete - Delete template file\n\n"
   printf "Alias: d, del, rm\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli templates delete TEMPLATE\n"
-  printf "  repli templates delete --help | -h\n"
+  printf "  repli template delete TEMPLATE\n"
+  printf "  repli template delete --help | -h\n"
   echo
 
   # :command.long_usage
@@ -549,14 +549,14 @@ repli_templates_delete_usage() {
 }
 
 # :command.usage
-repli_files_usage() {
-  printf "repli files - Manage uploaded files\n\n"
+repli_file_usage() {
+  printf "repli file - Manage uploaded files\n\n"
   printf "Alias: f\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli files COMMAND\n"
-  printf "  repli files [COMMAND] --help | -h\n"
+  printf "  repli file COMMAND\n"
+  printf "  repli file [COMMAND] --help | -h\n"
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
@@ -578,14 +578,14 @@ repli_files_usage() {
 }
 
 # :command.usage
-repli_files_list_usage() {
-  printf "repli files list - Show list of uploaded files\n\n"
+repli_file_list_usage() {
+  printf "repli file list - Show list of uploaded files\n\n"
   printf "Alias: ls\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli files list [OPTIONS]\n"
-  printf "  repli files list --help | -h\n"
+  printf "  repli file list [OPTIONS]\n"
+  printf "  repli file list --help | -h\n"
   echo
 
   # :command.long_usage
@@ -613,19 +613,19 @@ repli_files_list_usage() {
 }
 
 # :command.usage
-repli_files_upload_usage() {
+repli_file_upload_usage() {
   if [[ -n $long_usage ]]; then
-    printf "repli files upload\n\n"
+    printf "repli file upload\n\n"
     printf "  Upload a file to Replicate\n  Note that under normal conditions, there should be no reason for you to use\n  this directly. Files will be uploaded automatically as needed.\n\n"
   else
-    printf "repli files upload - Upload a file to Replicate\n\n"
+    printf "repli file upload - Upload a file to Replicate\n\n"
   fi
   printf "Alias: u\n"
   echo
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  repli files upload FILE\n"
-  printf "  repli files upload --help | -h\n"
+  printf "  repli file upload FILE\n"
+  printf "  repli file upload --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1324,9 +1324,9 @@ repli_info_command() {
 }
 
 # :command.function
-repli_templates_new_command() {
+repli_template_new_command() {
 
-  # src/commands/templates/new.sh
+  # src/commands/template/new.sh
   model="${args[model]}"
   name="${args[--name]}"
   force="${args[--force]}"
@@ -1352,18 +1352,18 @@ repli_templates_new_command() {
 }
 
 # :command.function
-repli_templates_list_command() {
+repli_template_list_command() {
 
-  # src/commands/templates/list.sh
+  # src/commands/template/list.sh
   search="${args[search]}"
   show_templates_list "$search"
 
 }
 
 # :command.function
-repli_templates_show_command() {
+repli_template_show_command() {
 
-  # src/commands/templates/show.sh
+  # src/commands/template/show.sh
   template="${args[template]}"
   file="$templates_dir/$template.yaml"
   yq -P -oy "$file"
@@ -1371,9 +1371,9 @@ repli_templates_show_command() {
 }
 
 # :command.function
-repli_templates_edit_command() {
+repli_template_edit_command() {
 
-  # src/commands/templates/edit.sh
+  # src/commands/template/edit.sh
   template="${args[template]}"
   file="$templates_dir/$template.yaml"
   "${EDITOR}" "$file"
@@ -1381,9 +1381,9 @@ repli_templates_edit_command() {
 }
 
 # :command.function
-repli_templates_delete_command() {
+repli_template_delete_command() {
 
-  # src/commands/templates/delete.sh
+  # src/commands/template/delete.sh
   template="${args[template]}"
   file="$templates_dir/$template.yaml"
   log info "deleting $file"
@@ -1392,9 +1392,9 @@ repli_templates_delete_command() {
 }
 
 # :command.function
-repli_files_list_command() {
+repli_file_list_command() {
 
-  # src/commands/files/list.sh
+  # src/commands/file/list.sh
   plain="${args[--plain]}"
   json="${args[--json]}"
 
@@ -1412,9 +1412,9 @@ repli_files_list_command() {
 }
 
 # :command.function
-repli_files_upload_command() {
+repli_file_upload_command() {
 
-  # src/commands/files/upload.sh
+  # src/commands/file/upload.sh
   file="${args[file]}"
   files_list="$output_dir/files.ini"
 
@@ -1574,17 +1574,17 @@ parse_requirements() {
       shift $#
       ;;
 
-    templates | t)
-      action="templates"
+    template | t)
+      action="template"
       shift
-      repli_templates_parse_requirements "$@"
+      repli_template_parse_requirements "$@"
       shift $#
       ;;
 
-    files | f)
-      action="files"
+    file | f)
+      action="file"
       shift
-      repli_files_parse_requirements "$@"
+      repli_file_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2104,7 +2104,7 @@ repli_info_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_templates_parse_requirements() {
+repli_template_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2113,7 +2113,7 @@ repli_templates_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_templates_usage
+        repli_template_usage
         exit
         ;;
 
@@ -2133,41 +2133,41 @@ repli_templates_parse_requirements() {
     new | n | add)
       action="new"
       shift
-      repli_templates_new_parse_requirements "$@"
+      repli_template_new_parse_requirements "$@"
       shift $#
       ;;
 
     list | ls)
       action="list"
       shift
-      repli_templates_list_parse_requirements "$@"
+      repli_template_list_parse_requirements "$@"
       shift $#
       ;;
 
     show | s)
       action="show"
       shift
-      repli_templates_show_parse_requirements "$@"
+      repli_template_show_parse_requirements "$@"
       shift $#
       ;;
 
     edit | e)
       action="edit"
       shift
-      repli_templates_edit_parse_requirements "$@"
+      repli_template_edit_parse_requirements "$@"
       shift $#
       ;;
 
     delete | d | del | rm)
       action="delete"
       shift
-      repli_templates_delete_parse_requirements "$@"
+      repli_template_delete_parse_requirements "$@"
       shift $#
       ;;
 
     # :command.command_fallback
     "")
-      repli_templates_usage >&2
+      repli_template_usage >&2
       exit 1
       ;;
 
@@ -2202,7 +2202,7 @@ repli_templates_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_templates_new_parse_requirements() {
+repli_template_new_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2211,7 +2211,7 @@ repli_templates_new_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_templates_new_usage
+        repli_template_new_usage
         exit
         ;;
 
@@ -2223,7 +2223,7 @@ repli_templates_new_parse_requirements() {
   done
 
   # :command.command_filter
-  action="templates new"
+  action="template new"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2275,7 +2275,7 @@ repli_templates_new_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['model']+x} ]]; then
-    printf "missing required argument: MODEL\nusage: repli templates new MODEL [OPTIONS]\n" >&2
+    printf "missing required argument: MODEL\nusage: repli template new MODEL [OPTIONS]\n" >&2
     # :command.examples_on_error
     printf "examples:\n" >&2
     printf "  repli add google/nano-banana banana\n" >&2
@@ -2299,7 +2299,7 @@ repli_templates_new_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_templates_list_parse_requirements() {
+repli_template_list_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2308,7 +2308,7 @@ repli_templates_list_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_templates_list_usage
+        repli_template_list_usage
         exit
         ;;
 
@@ -2320,7 +2320,7 @@ repli_templates_list_parse_requirements() {
   done
 
   # :command.command_filter
-  action="templates list"
+  action="template list"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2359,7 +2359,7 @@ repli_templates_list_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_templates_show_parse_requirements() {
+repli_template_show_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2368,7 +2368,7 @@ repli_templates_show_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_templates_show_usage
+        repli_template_show_usage
         exit
         ;;
 
@@ -2380,7 +2380,7 @@ repli_templates_show_parse_requirements() {
   done
 
   # :command.command_filter
-  action="templates show"
+  action="template show"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2411,7 +2411,7 @@ repli_templates_show_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['template']+x} ]]; then
-    printf "missing required argument: TEMPLATE\nusage: repli templates show TEMPLATE\n" >&2
+    printf "missing required argument: TEMPLATE\nusage: repli template show TEMPLATE\n" >&2
 
     exit 1
   fi
@@ -2436,7 +2436,7 @@ repli_templates_show_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_templates_edit_parse_requirements() {
+repli_template_edit_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2445,7 +2445,7 @@ repli_templates_edit_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_templates_edit_usage
+        repli_template_edit_usage
         exit
         ;;
 
@@ -2463,7 +2463,7 @@ repli_templates_edit_parse_requirements() {
   env_var_names+=("EDITOR")
 
   # :command.command_filter
-  action="templates edit"
+  action="template edit"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2494,7 +2494,7 @@ repli_templates_edit_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['template']+x} ]]; then
-    printf "missing required argument: TEMPLATE\nusage: repli templates edit TEMPLATE\n" >&2
+    printf "missing required argument: TEMPLATE\nusage: repli template edit TEMPLATE\n" >&2
 
     exit 1
   fi
@@ -2519,7 +2519,7 @@ repli_templates_edit_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_templates_delete_parse_requirements() {
+repli_template_delete_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2528,7 +2528,7 @@ repli_templates_delete_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_templates_delete_usage
+        repli_template_delete_usage
         exit
         ;;
 
@@ -2540,7 +2540,7 @@ repli_templates_delete_parse_requirements() {
   done
 
   # :command.command_filter
-  action="templates delete"
+  action="template delete"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2571,7 +2571,7 @@ repli_templates_delete_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['template']+x} ]]; then
-    printf "missing required argument: TEMPLATE\nusage: repli templates delete TEMPLATE\n" >&2
+    printf "missing required argument: TEMPLATE\nusage: repli template delete TEMPLATE\n" >&2
 
     exit 1
   fi
@@ -2596,7 +2596,7 @@ repli_templates_delete_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_files_parse_requirements() {
+repli_file_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2605,7 +2605,7 @@ repli_files_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_files_usage
+        repli_file_usage
         exit
         ;;
 
@@ -2625,20 +2625,20 @@ repli_files_parse_requirements() {
     list | ls)
       action="list"
       shift
-      repli_files_list_parse_requirements "$@"
+      repli_file_list_parse_requirements "$@"
       shift $#
       ;;
 
     upload | u)
       action="upload"
       shift
-      repli_files_upload_parse_requirements "$@"
+      repli_file_upload_parse_requirements "$@"
       shift $#
       ;;
 
     # :command.command_fallback
     "")
-      repli_files_usage >&2
+      repli_file_usage >&2
       exit 1
       ;;
 
@@ -2673,7 +2673,7 @@ repli_files_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_files_list_parse_requirements() {
+repli_file_list_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2682,7 +2682,7 @@ repli_files_list_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_files_list_usage
+        repli_file_list_usage
         exit
         ;;
 
@@ -2694,7 +2694,7 @@ repli_files_list_parse_requirements() {
   done
 
   # :command.command_filter
-  action="files list"
+  action="file list"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2735,7 +2735,7 @@ repli_files_list_parse_requirements() {
 }
 
 # :command.parse_requirements
-repli_files_upload_parse_requirements() {
+repli_file_upload_parse_requirements() {
   local key
 
   # :command.fixed_flags_filter
@@ -2744,7 +2744,7 @@ repli_files_upload_parse_requirements() {
     case "$key" in
       --help | -h)
         long_usage=yes
-        repli_files_upload_usage
+        repli_file_upload_usage
         exit
         ;;
 
@@ -2756,7 +2756,7 @@ repli_files_upload_parse_requirements() {
   done
 
   # :command.command_filter
-  action="files upload"
+  action="file upload"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2787,7 +2787,7 @@ repli_files_upload_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['file']+x} ]]; then
-    printf "missing required argument: FILE\nusage: repli files upload FILE\n" >&2
+    printf "missing required argument: FILE\nusage: repli file upload FILE\n" >&2
 
     exit 1
   fi
@@ -2850,15 +2850,15 @@ run() {
     "show") repli_show_command ;;
     "env") repli_env_command ;;
     "info") repli_info_command ;;
-    "templates") repli_templates_command ;;
-    "templates new") repli_templates_new_command ;;
-    "templates list") repli_templates_list_command ;;
-    "templates show") repli_templates_show_command ;;
-    "templates edit") repli_templates_edit_command ;;
-    "templates delete") repli_templates_delete_command ;;
-    "files") repli_files_command ;;
-    "files list") repli_files_list_command ;;
-    "files upload") repli_files_upload_command ;;
+    "template") repli_template_command ;;
+    "template new") repli_template_new_command ;;
+    "template list") repli_template_list_command ;;
+    "template show") repli_template_show_command ;;
+    "template edit") repli_template_edit_command ;;
+    "template delete") repli_template_delete_command ;;
+    "file") repli_file_command ;;
+    "file list") repli_file_list_command ;;
+    "file upload") repli_file_upload_command ;;
   esac
 }
 
